### ISSUE TITLE
[Remoto] [DEV SR VTEX IO - PJ] na [K2]

### ISSUE THREAD

**Issue by Vitorrecilhas** [remotejobsbr/trabalho-remoto-vagas#11]
👇Requisitos Obrigatórios
● Experiência com VTEX IO (desenvolvimento front-end e versionamento);
● Conhecimento prático de JavaScript, HTML5, CSS3, React, WebPack, NodeJS, e
os mais recentes padrões JavaScript;
● Familiaridade com GraphQL;
● Experiência de construção de aplicativos web ricos em dados consumindo
serviços RESTful e APIs;
● Versionamento de projetos com GIT, GITHUB e Bitbucket;
● Familiaridade com Metodologias Ágeis.

👇Diferenciais
● Familiaridade com Gatsby e JamStack;
● Testes unitários e testes integrados (Jest, Cypress, etc.);
● Conhecimentos em SEO e acessibilidade.

📧📥Mais detalhes: [vmartins@k2partnering.com](mailto:vmartins@k2partnering.com)

🟢WhatsApp Comercial: (11) 98173-5709

👍💙Compartilhe ou curta para chegar em mais pessoas: https://lnkd.in/drX3ACY7

**Comment by guibranco** [comment]
Essa vaga ainda esta aberta ?
