### ISSUE TITLE
[Remoto/SP] [Dev FullStack Senior] na [K2]

### ISSUE THREAD

**Issue by Vitorrecilhas** [remotejobsbr/trabalho-remoto-vagas#13]
## Descrição da vaga

• Solida experiência com desenvolvimento em fullstack (Back e Front) Node.js e React.js
• Experience com AWS - Obrigatório
• Experience com Velocity (desejavel)
• Experience com DevOps (Jenkins/Codebuild etc..)
• Experience com Graph DBs (desejavel)
• Bons conhecimento de arquitetura cloud e implementação
• Inglês Avançado
• Experiência e compreensão de planejamento de projetos de supply
• Bacharel em Computer Science, Engineering, or Technical Field

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para [vmartins@k2partnering.com](mailto:vmartins@k2partnering.com)

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior

**Comment by guibranco** [comment]
Essa vaga ainda esta aberta ?
