### ISSUE TITLE
GH Action - Stale não está sendo executada

### ISSUE THREAD

**Issue by guibranco** [remotejobsbr/trabalho-remoto-vagas#21]
Bom dia @IsTheJack , a action de fechar as issues antigas não está sendo executada, poderia verificar por gentileza ? 

https://github.com/remotejobsbr/trabalho-remoto-vagas/actions/workflows/stale-issues.yml

**Comment by guibranco** [comment]
@IsTheJack consegue ver essa issue aqui ?

**Comment by IsTheJack** [comment]
Olá @guibranco. Perdão pela demora. Assim que eu tiver um tempinho eu corrijo o repositório

**Comment by guibranco** [comment]
@IsTheJack abri uma PR para arrumar: #22

**Comment by guibranco** [comment]
@IsTheJack consegue dar uma olhada?
