### ISSUE TITLE
[REMOTO] Full Stack Developer C# Pleno na Rheserva Consultoria

### ISSUE THREAD

**Issue by matheusfgalvao** [remotejobsbr/trabalho-remoto-vagas#4]
## Nossa empresa

Venha iniciar uma nova Jornada Profissional repleta de oportunidades e desenvolver um novo olhar sobre carreira e trabalho!

Trabalhe em uma empresa consolidada com profissionais experientes, oferecendo um sistema que é uma **solução inteligente** capaz de realizar rastreamento preventivo de vulnerabilidades e riscos fiscais. Para que isso seja possível é aplicada uma **metodologia diferenciada** de revisão digital de tributos federais com **tecnologia própria e patenteada**. Como missão, contribuímos com soluções seguras e sustentáveis, que protejam e melhorem a saúde fiscal e financeira das empresas.

## Descrição da vaga

Como **Developer Full Stack C#** você será responsável por manter e desenvolver novas funcionalidades dos nossos produtos e serviços.

E para isso, esperamos que você possua os seguintes conhecimentos:

- Desenvolvimento WEB: C#, JavaScript, HTML, CSS, Typescript e Angular;
- ASP.NET (MVC5) e ASP.NET Core
- Entity Framework
- DDD
- SQL Server
- Inglês técnico para a área de TI

## Local

Atuação **100% REMOTA**

## Benefícios

- Vale transporte
- Vale alimentação
- Plano de Saúde

## Contratação

Regime de contratação CLT

## Como se candidatar

Por favor envie um email para matheus.fajardo@rheserva.com.br com seu CV anexado - enviar no assunto: **Full Stack Developer C#**

#### Categoria

- Front-End
- Back-End

#### Alocação

- Remoto

#### Regime

- CLT

#### Nível

- Pleno

**Comment by guibranco** [comment]
Essa vaga ainda esta aberta ?
