### ISSUE TITLE
[Remoto] [Desenvolvedor Full Stack NodeJS] na [SVA Tech]

### ISSUE THREAD

**Issue by YsllaSantos** [remotejobsbr/trabalho-remoto-vagas#5]
A SVA Tech desenvolve soluções inovadoras que transformam simples câmeras de segurança em aparelhos inteligentes através da tecnologia de vídeo analítico. Com uma equipe com mais de 15 anos de experiência no segmento de segurança e monitoramento, somos uma empresa de tecnologia e inovação que desenvolve softwares e hardwares exclusivos através inteligência artificial, deep learning e visão computacional.
Em outras palavras, estamos sempre em busca de novas soluções automatizadas e inteligentes para garantir a segurança de sua empresa e sua tranquilidade.
 
Responsabilidades:
 
Colaborar na construção dos nossos produtos;
Atuar com protagonismo no desenvolvimento e evolução das nossas tecnologias como um full stack;
Operar no ciclo completo de desenvolvimento do software, com foco principal em codificação. 
Realizar atividades de especificação, inspeção de código, testes e implantação.

Requisitos e qualificações:

Experiência em desenvolvimento de aplicações Web (front end e back end) utilizando JavaScript (Node.js).
Ter atuado em tecnologias associadas (Angular, Express, MongoDB, etc.).
Vivência em desenvolvimento de Apps para dispositivos móveis baseados no framework Ionic/Cordova, usando TypeScript/JavaScript, HTML5 e CSS3. 
Conhecimento em ferramentas de controle de versão (Git).
Conhecimento de Inglês Intermediário.
 
 
Desejável:
 
Conhecimento em metodologias ágeis.
 
 
Benefícios:
 
Salário a combinar;
Vale-refeição para usar a vontade;
Horário flexível;
Vale-transporte de acordo com a necessidade;
Plano de saúde;
Dress code flexível.

## Contratação

CLT

## Como se candidatar

Envie seu currículo para rh.sva@svatech.com.br e visite nosso site para nos conhecer melhor svatech.com.br

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 20 dias após cada processo.
E-mail para contato em caso de não haver resposta: rh.sva@svatech.com.br

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Júnior
- Pleno
- Sênior
- Especialista

**Comment by guibranco** [comment]
Essa vaga ainda esta aberta ?
