### ISSUE TITLE
[Remoto] [Software Engineer] na [K2]

### ISSUE THREAD

**Issue by Vitorrecilhas** [remotejobsbr/trabalho-remoto-vagas#8]
⏳Oportunidade de Hoje - Engenheiro de Software PJ Remoto:

Responsabilidades do cargo
Participação no desenvolvimento/atualização de especificações funcionais para mudanças de programação
Colaborar com outras equipes para desenvolver soluções ou concluir alterações/correções
Capaz de realizar testes de unidade/integração e/ou regressão
Desenvolvimento/atualização de documentação (Sistema e usuário)
Fornecer comunicação proativa sobre interrupções do sistema, problemas ou soluções alternativas
Identificando/propondo correções e entregando melhorias contínuas

Deve ter:
Boa comunicação verbal e escrita em inglês
Capacidade de trabalhar remotamente de clientes e alguns membros da equipe
Excelentes habilidades interpessoais e de colaboração, trabalho em equipe
Experiência anterior em suporte a projetos e aplicativos Agile (é bom ter operações de servidor e desktop também)
Habilidades analíticas e de resolução de problemas (solução de problemas)

Habilidades de desenvolvimento:
- Front-end - Angular, HTML5, CSS3 
- Back-end - C# / .NET Core, Entity Framework Core 
- Teste de unidade (TDD é um plus) - Git - Estes são um plus: Java, WPF e WCF, C /C++, Python, PowerShell, etc.
Nuvem - Conhecimento básico do Azure - Azure DevOps - Autenticação moderna - OpenID Connect (usuário final), fluxo de credenciais do cliente (serviço a serviço), etc.
Habilidades de banco de dados - Microsoft SQL Server - Oracle é uma vantagem

📧📥Mais detalhes: vmartins@k2partnering.com

🟢WhatsApp Comercial: (11) 98173-5709 - https://wa.me/5511981735709

👍💙Compartilhe ou curta para chegar em mais pessoas: https://www.linkedin.com/feed/update/urn:li:activity:6917912885276934144/

**Comment by guibranco** [comment]
Essa vaga ainda esta aberta ?
